---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - aks.azure.com
  resources:
  - gateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aks.azure.com
  resources:
  - gateways/finalizers
  verbs:
  - update
- apiGroups:
  - aks.azure.com
  resources:
  - gateways/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - aks.azure.com
  resources:
  - peers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aks.azure.com
  resources:
  - peers/finalizers
  verbs:
  - update
- apiGroups:
  - aks.azure.com
  resources:
  - peers/status
  verbs:
  - get
  - patch
  - update
