apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: konnectivity-webhook
webhooks:
  - name: konnectivity-webhook.kube-system.svc
    clientConfig:
      service:
        name: konnectivity-webhook
        namespace: kube-system
        path: /mutate
      caBundle: <base64-encoded-ca>
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
