apiVersion: aks.azure.com/v1alpha1
kind: Peer
metadata:
  labels:
    app.kubernetes.io/name: aks-mesh
    app.kubernetes.io/managed-by: kustomize
  name: peer-sample
spec:
  # TODO(user): Add fields here
  publicKey: "samplePublicKey"
  podIPs: 
    - "10.244.0.2"
  endpoint: "10.0.0.2:51820"
